### ISSUE TITLE
Usage of std::string_view in decoder

### ISSUE THREAD

**Issue by divaykin** [iodcpp/metajson#12]
Is it feasible to decode json strings as std::string_view instead of std::string? It can save memory allocation from heap + memcpy on every string if you'd manage to just wrap characters in input buffer into std::string_view.

**Comment by matt-42** [comment]
Not yet, the problem is that to handle utf8 we need to generate a new decoded string.
Would you like to skip UTF8 decoding ? This could be possible but it is not implemented yet.

**Comment by matt-42** [comment]
The problem is that we
