### ISSUE TITLE
License of metajson

### ISSUE THREAD

**Issue by haisongdong-harrison** [iodcpp/metajson#13]
Hi Matt, I found your nice project and it looks so cool so I would like to try it myself.
But there's no license attached which falls back to all rights reserved. 

So I was wondering if you could kindly add a license for people to play with it?
Thanks!

**Comment by matt-42** [comment]
yes. Thanks for the report. I'll put the MIT licence.

**Comment by haisongdong-harrison** [comment]
Thank you so much!
